//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.FAQPlusPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.FAQPlusPlus.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new question details.
        /// </summary>
        public static string AddQuestionSubtitle {
            get {
                return ResourceManager.GetString("AddQuestionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a **Answer:**.
        /// </summary>
        public static string AnswerTitle {
            get {
                return ResourceManager.GetString("AnswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type your feedback (500 characters max).
        /// </summary>
        public static string AppFeedbackDescriptionPlaceholderText {
            get {
                return ResourceManager.GetString("AppFeedbackDescriptionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta a un Asesor RH.
        /// </summary>
        public static string AskAnExpertButtonText {
            get {
                return ResourceManager.GetString("AskAnExpertButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta a un Asesor RH.
        /// </summary>
        public static string AskAnExpertDisplayText {
            get {
                return ResourceManager.GetString("AskAnExpertDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu pregunta con todo el detalle posible en este espacio (500 caracteres como máximo).
        /// </summary>
        public static string AskAnExpertPlaceholderText {
            get {
                return ResourceManager.GetString("AskAnExpertPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One of our experts will reach out to you soon..
        /// </summary>
        public static string AskAnExpertSubheaderText {
            get {
                return ResourceManager.GetString("AskAnExpertSubheaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a … Si mi respuesta no te ayuda … Te puedo contactar con un Asesor RH..
        /// </summary>
        public static string AskAnExpertText2 {
            get {
                return ResourceManager.GetString("AskAnExpertText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta a un Asesor RH.
        /// </summary>
        public static string AskAnExpertTitleText {
            get {
                return ResourceManager.GetString("AskAnExpertTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu solicitud ha sido asignada a un Asesor RH. Pronto te buscará en otro chat..
        /// </summary>
        public static string AssignedTicketUserNotification {
            get {
                return ResourceManager.GetString("AssignedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assigned.
        /// </summary>
        public static string AssignedUserNotificationStatus {
            get {
                return ResourceManager.GetString("AssignedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assign to me.
        /// </summary>
        public static string AssignToMeActionChoiceTitle {
            get {
                return ResourceManager.GetString("AssignToMeActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BackButton.
        /// </summary>
        public static string BackButtonCommandText {
            get {
                return ResourceManager.GetString("BackButtonCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar estatus.
        /// </summary>
        public static string ChangeStatusButtonText {
            get {
                return ResourceManager.GetString("ChangeStatusButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chatea con {0}.
        /// </summary>
        public static string ChatTextButton {
            get {
                return ResourceManager.GetString("ChatTextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string CloseActionChoiceTitle {
            get {
                return ResourceManager.GetString("CloseActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado: .
        /// </summary>
        public static string ClosedFactTitle {
            get {
                return ResourceManager.GetString("ClosedFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta solicitud ha sido cerrada. Pregnta a un Asesor RH nuevamente si necesitas mas ayuda..
        /// </summary>
        public static string ClosedTicketUserNotification {
            get {
                return ResourceManager.GetString("ClosedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closed.
        /// </summary>
        public static string ClosedUserNotificationStatus {
            get {
                return ResourceManager.GetString("ClosedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No encontré una respuesta para tu consulta. ¿Quieres que le pregunte a un Asesor RH?.
        /// </summary>
        public static string CustomMessage {
            get {
                return ResourceManager.GetString("CustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado: .
        /// </summary>
        public static string DateCreatedDisplayFactTitle {
            get {
                return ResourceManager.GetString("DateCreatedDisplayFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} at {1}.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this item? The question and answer will both be deleted..
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleted by {0}.
        /// </summary>
        public static string DeletedQnaPair {
            get {
                return ResourceManager.GetString("DeletedQnaPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description:.
        /// </summary>
        public static string DescriptionFact {
            get {
                return ResourceManager.GetString("DescriptionFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Description (Markdown supported).
        /// </summary>
        public static string DescriptionLabelText {
            get {
                return ResourceManager.GetString("DescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter information (500 characters max).
        /// </summary>
        public static string DescriptionPlaceholderText {
            get {
                return ResourceManager.GetString("DescriptionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción..
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit question details.
        /// </summary>
        public static string EditQuestionSubtitle {
            get {
                return ResourceManager.GetString("EditQuestionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description cannot be empty..
        /// </summary>
        public static string EmptyDescriptionErrorText {
            get {
                return ResourceManager.GetString("EmptyDescriptionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image url can not be empty..
        /// </summary>
        public static string EmptyImageUrlErrorText {
            get {
                return ResourceManager.GetString("EmptyImageUrlErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question text cannot be empty..
        /// </summary>
        public static string EmptyQuestionErrorText {
            get {
                return ResourceManager.GetString("EmptyQuestionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title cannot be empty..
        /// </summary>
        public static string EmptyTitleErrorText {
            get {
                return ResourceManager.GetString("EmptyTitleErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Created by.
        /// </summary>
        public static string EntryCreatedByText {
            get {
                return ResourceManager.GetString("EntryCreatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Something went wrong. Please try again later..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a **{0}** ha compartido su retroalimentación..
        /// </summary>
        public static string FeedbackAlertText {
            get {
                return ResourceManager.GetString("FeedbackAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu experiencia con todo el detalle aquí (500 caracteres como maximo).
        /// </summary>
        public static string FeedbackDescriptionPlaceholderText {
            get {
                return ResourceManager.GetString("FeedbackDescriptionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Was this answer helpful? (Required).
        /// </summary>
        public static string FeedbackRatingRequired {
            get {
                return ResourceManager.GetString("FeedbackRatingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartenos tu experiencia de como lo estoy haciendo para que me ayudes a mejorar..
        /// </summary>
        public static string FeedbackText1 {
            get {
                return ResourceManager.GetString("FeedbackText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realiza una pregunta.
        /// </summary>
        public static string FunctionCardText1 {
            get {
                return ResourceManager.GetString("FunctionCardText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo tienes que hacerme una pregunta y yo buscaré la mejor respuesta para ti. Si fuera necesario un seguimiento adicional, te aseguro que lo haré..
        /// </summary>
        public static string FunctionCardText2 {
            get {
                return ResourceManager.GetString("FunctionCardText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la solicitud original.
        /// </summary>
        public static string GoToOriginalThreadButtonText {
            get {
                return ResourceManager.GetString("GoToOriginalThreadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View details.
        /// </summary>
        public static string GoToThread {
            get {
                return ResourceManager.GetString("GoToThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Helpful.
        /// </summary>
        public static string HelpfulRatingText {
            get {
                return ResourceManager.GetString("HelpfulRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HTML tags are not supported..
        /// </summary>
        public static string HTMLErrorText {
            get {
                return ResourceManager.GetString("HTMLErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image URL.
        /// </summary>
        public static string ImageLabelText {
            get {
                return ResourceManager.GetString("ImageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter image URL (200 characters max).
        /// </summary>
        public static string ImageUrlPlaceholderText {
            get {
                return ResourceManager.GetString("ImageUrlPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image URL is not valid..
        /// </summary>
        public static string InvalidImageUrlErrorText {
            get {
                return ResourceManager.GetString("InvalidImageUrlErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redirect URL is not valid..
        /// </summary>
        public static string InvalidRedirectUrlText {
            get {
                return ResourceManager.GetString("InvalidRedirectUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last edited by.
        /// </summary>
        public static string LastEditedText {
            get {
                return ResourceManager.GetString("LastEditedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo de título es obligatorio..
        /// </summary>
        public static string MandatoryTitleFieldText {
            get {
                return ResourceManager.GetString("MandatoryTitleFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manually added question.
        /// </summary>
        public static string ManuallyAddedQuestionMessage {
            get {
                return ResourceManager.GetString("ManuallyAddedQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Needs Improvement.
        /// </summary>
        public static string NeedsImprovementRatingText {
            get {
                return ResourceManager.GetString("NeedsImprovementRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La extensión del mensajería solo puede ser invocado desde el canal en el cual la aplicación está instalada.
        /// </summary>
        public static string NonSMEErrorText {
            get {
                return ResourceManager.GetString("NonSMEErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not helpful.
        /// </summary>
        public static string NotHelpfulRatingText {
            get {
                return ResourceManager.GetString("NotHelpfulRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acabo de compartir tu pregunta con el equipo. Pronto te buscará un Asesor RH en otro chat..
        /// </summary>
        public static string NotificationCardContent {
            get {
                return ResourceManager.GetString("NotificationCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open article.
        /// </summary>
        public static string OpenArticle {
            get {
                return ResourceManager.GetString("OpenArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optional Fields.
        /// </summary>
        public static string OptionalFieldDisplayText {
            get {
                return ResourceManager.GetString("OptionalFieldDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        public static string PreviewButtonText {
            get {
                return ResourceManager.GetString("PreviewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question already exist. please add different question..
        /// </summary>
        public static string QuestionAlreadyExistsErrorText {
            get {
                return ResourceManager.GetString("QuestionAlreadyExistsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta realizada:.
        /// </summary>
        public static string QuestionAskedFactTitle {
            get {
                return ResourceManager.GetString("QuestionAskedFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a **{0}** solicita ayuda..
        /// </summary>
        public static string QuestionForExpertSubHeaderText {
            get {
                return ResourceManager.GetString("QuestionForExpertSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Question.
        /// </summary>
        public static string QuestionLabelText {
            get {
                return ResourceManager.GetString("QuestionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter information (100 characters max).
        /// </summary>
        public static string QuestionPlaceholderText {
            get {
                return ResourceManager.GetString("QuestionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a **Question:** {0}.
        /// </summary>
        public static string QuestionTitle {
            get {
                return ResourceManager.GetString("QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rating is mandatory.
        /// </summary>
        public static string RatingMandatoryText {
            get {
                return ResourceManager.GetString("RatingMandatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rating.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redirection URL.
        /// </summary>
        public static string RedirectionLabelText {
            get {
                return ResourceManager.GetString("RedirectionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter information (200 characters max).
        /// </summary>
        public static string RedirectionUrlPlaceholderText {
            get {
                return ResourceManager.GetString("RedirectionUrlPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reopen.
        /// </summary>
        public static string ReopenActionChoiceTitle {
            get {
                return ResourceManager.GetString("ReopenActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reopen and assign to me.
        /// </summary>
        public static string ReopenAssignToMeActionChoiceTitle {
            get {
                return ResourceManager.GetString("ReopenAssignToMeActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu solicitud está abierta nuevamente. Un Asesor RH te enviará un mensaje en otro chat..
        /// </summary>
        public static string ReopenedTicketUserNotification {
            get {
                return ResourceManager.GetString("ReopenedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aquí está lo que encontré:.
        /// </summary>
        public static string ResponseHeaderText {
            get {
                return ResourceManager.GetString("ResponseHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retroalimentación.
        /// </summary>
        public static string ResultsFeedbackText {
            get {
                return ResourceManager.GetString("ResultsFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a **{0}**.
        /// </summary>
        public static string SelectActionItemDisplayTextFormatting {
            get {
                return ResourceManager.GetString("SelectActionItemDisplayTextFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How helpful is this app? (Required).
        /// </summary>
        public static string ShareAppFeedbackRating {
            get {
                return ResourceManager.GetString("ShareAppFeedbackRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartenos tu experiencia..
        /// </summary>
        public static string ShareFeedbackButtonText {
            get {
                return ResourceManager.GetString("ShareFeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartir retroalimentación.
        /// </summary>
        public static string ShareFeedbackDisplayText {
            get {
                return ResourceManager.GetString("ShareFeedbackDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartir retroalimentación sobre el chatbot..
        /// </summary>
        public static string ShareFeedbackTitleText {
            get {
                return ResourceManager.GetString("ShareFeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe un título corto (50 caracteres máximo).
        /// </summary>
        public static string ShowCardTitleText {
            get {
                return ResourceManager.GetString("ShowCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta solicitud ha sido asignada. Asignada a {0}..
        /// </summary>
        public static string SMEAssignedStatus {
            get {
                return ResourceManager.GetString("SMEAssignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta solicitud ha sido cerrada. Fue cerrada por {0}..
        /// </summary>
        public static string SMEClosedStatus {
            get {
                return ResourceManager.GetString("SMEClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Feedback.
        /// </summary>
        public static string SMEFeedbackHeaderText {
            get {
                return ResourceManager.GetString("SMEFeedbackHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta solicitud no ha sido asignada. Última actualización realizada por {0}. .
        /// </summary>
        public static string SMEOpenedStatus {
            get {
                return ResourceManager.GetString("SMEOpenedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assigned to {0}.
        /// </summary>
        public static string SMETicketAssignedStatus {
            get {
                return ResourceManager.GetString("SMETicketAssignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closed.
        /// </summary>
        public static string SMETicketClosedStatus {
            get {
                return ResourceManager.GetString("SMETicketClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unassigned.
        /// </summary>
        public static string SMETicketUnassignedStatus {
            get {
                return ResourceManager.GetString("SMETicketUnassignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RE: {0}.
        /// </summary>
        public static string SMEUserChatMessage {
            get {
                return ResourceManager.GetString("SMEUserChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus: .
        /// </summary>
        public static string StatusFactTitle {
            get {
                return ResourceManager.GetString("StatusFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtitle (Markdown supported).
        /// </summary>
        public static string SubtitleLabelText {
            get {
                return ResourceManager.GetString("SubtitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter information (20 characters max).
        /// </summary>
        public static string SubtitlePlaceholderText {
            get {
                return ResourceManager.GetString("SubtitlePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The optional fields below can be used to add additional details to the answer..
        /// </summary>
        public static string SuggestedText {
            get {
                return ResourceManager.GetString("SuggestedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tour del equipo.
        /// </summary>
        public static string TakeATeamTourButtonText {
            get {
                return ResourceManager.GetString("TakeATeamTourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take a tour.
        /// </summary>
        public static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dá un clic en el botón de chat con el usuario para iniciar un chat directo..
        /// </summary>
        public static string TeamChatContent {
            get {
                return ResourceManager.GetString("TeamChatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar chat con usuarios.
        /// </summary>
        public static string TeamChatHeaderText {
            get {
                return ResourceManager.GetString("TeamChatHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedo responder a comandos dentro de los canales. Toma un tour rápido de mis capacidades..
        /// </summary>
        public static string TeamCustomMessage {
            get {
                return ResourceManager.GetString("TeamCustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puedes ver que tipo de ayuda necesitan los usuarios..
        /// </summary>
        public static string TeamNotificationContent {
            get {
                return ResourceManager.GetString("TeamNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibe notificaciones de usuarios finales.
        /// </summary>
        public static string TeamNotificationHeaderText {
            get {
                return ResourceManager.GetString("TeamNotificationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione consultas asignadas o cerradas para el seguimiento de las consultas..
        /// </summary>
        public static string TeamTicketSystemContent {
            get {
                return ResourceManager.GetString("TeamTicketSystemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de consultas.
        /// </summary>
        public static string TeamTicketSystemHeaderText {
            get {
                return ResourceManager.GetString("TeamTicketSystemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Gracias por tus comentarios! Los compartire con los Asesores RH. Esto me ayuda a aprender y mejorar..
        /// </summary>
        public static string ThankYouTextContent {
            get {
                return ResourceManager.GetString("ThankYouTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title:.
        /// </summary>
        public static string TitleFact {
            get {
                return ResourceManager.GetString("TitleFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title (Markdown supported).
        /// </summary>
        public static string TitleLabelText {
            get {
                return ResourceManager.GetString("TitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter information (50 characters max).
        /// </summary>
        public static string TitlePlaceholderText {
            get {
                return ResourceManager.GetString("TitlePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title (Required).
        /// </summary>
        public static string TitleRequiredText {
            get {
                return ResourceManager.GetString("TitleRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unassign.
        /// </summary>
        public static string UnassignActionChoiceTitle {
            get {
                return ResourceManager.GetString("UnassignActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unassigned.
        /// </summary>
        public static string UnassignedUserNotificationStatus {
            get {
                return ResourceManager.GetString("UnassignedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update history.
        /// </summary>
        public static string UpdateHistoryButtonText {
            get {
                return ResourceManager.GetString("UpdateHistoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string UpdateHistoryDateHeaderText {
            get {
                return ResourceManager.GetString("UpdateHistoryDateHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name|Action|Date.
        /// </summary>
        public static string UpdateHistoryHeadersText {
            get {
                return ResourceManager.GetString("UpdateHistoryHeadersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View article.
        /// </summary>
        public static string ViewArticleButtonText {
            get {
                return ResourceManager.GetString("ViewArticleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait for some time, updates to this question: &quot;{0}&quot; will be available in short time..
        /// </summary>
        public static string WaitMessage {
            get {
                return ResourceManager.GetString("WaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Note: Updates are made every few minutes.
        /// </summary>
        public static string WaitMessageAnswer {
            get {
                return ResourceManager.GetString("WaitMessageAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello team,   
        ///
        ///I am your friendly Q&amp;A bot that helps you provide support to people who interact with me and need more assistance..
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
